name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: List all environment variables
        run: env | sort

      - name: Check for CLOUDFLARE_API_TOKEN
        run: if [ -n "$CLOUDFLARE_API_TOKEN" ]; then echo "CLOUDFLARE_API_TOKEN is set"; else echo "CLOUDFLARE_API_TOKEN is not set"; fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Set up Bun
      - uses: oven-sh/setup-bun@v1

      # Install dependencies using Bun
      - run: bun install
      
      # Deploy based on branch
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: bun run deploy
        
      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        run: bun run build && wrangler deploy --env staging

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: bunx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # - run: bunx nx affected -t deploy
